### ISSUE TITLE
Trim feature is distorting story page, we can use blurred until item is resolved.

### ISSUE THREAD

**Issue by kamini1208** [mg2connext/connext#23] opened 2017-06-19 20:32 UTC
Trim feature is distorting story page, we can use blurred until item is resolved.

**Comment by mg2dael** [comment] 2017-06-20 15:52
This is caused by how your webpages are structured.  There's nothing the ConneXt team can do to fix it, unfortunately.

**Comment by mg2dael** [comment] 2017-06-27 11:06
@kamini1208 Can we close this issue?

**Comment by gborders** [comment] 2017-06-27 11:22
Yes

**Closed as completed** 2017-06-27 11:26 UTC
